### ISSUE TITLE
Random app crashes

### ISSUE THREAD

**Issue by FireCubeStudios** [FireCubeStudios/Clippy#1]
During development I occur random crashes that occurs without any meaningful debugging info (that I've been able to find) any help in investigating this would be appreciated.

Steps to reproduce:
- launch app
- change some features or add new features
 
This has been the biggest blocker for full release and has been puzzling me for a few days.

**Comment by veler** [comment]
By "feature", do you mean options? Or do you mean changing the code of a feature while debugging the app, and having Hot Reload / Visual Studio / Debugger making the app crashing?

**Comment by FireCubeStudios** [comment]
By feature I mean that simply modifying UI like the main window or chat message causes a random crash however subsequent runs don't get the crash for some reason
