### ISSUE TITLE
Clippy is not working.

### ISSUE THREAD

**Issue by figo2001** [FireCubeStudios/Clippy#17]
![clippy](https://github.com/FireCubeStudios/Clippy/assets/78696850/492fb8e8-c554-4255-901f-c5f8b591a876)
Whats the issue here??
I have already provided my API key but it does not woking properly.
Can you please help me to find out the error??

`Error { Code = , Message = You exceeded your current quota, please check your plan and billing details., Param = , Type = insufficient_quota }`

**Comment by FireCubeStudios** [comment]
Api key has token limits due to using a free account. Use a key that did have tokens

**Comment by figo2001** [comment]
Ok thank you for the information
