### ISSUE TITLE
Support for oobabooga's text-generation-webui API instead of OpenAi API key

### ISSUE THREAD

**Issue by Vexicle** [FireCubeStudios/Clippy#20]
This may be helpful for people who wish to run the AI without any costs, such as me. I think it'd be a cost effective solution, This is oobabooga's text-generation-webui: [https://github.com/oobabooga/text-generation-webui](url)

**Comment by FireCubeStudios** [comment]
does it uspport c#

**Comment by FireCubeStudios** [comment]
Hello I am closing this as I will add reverse proxy support instead #4
