### ISSUE TITLE
settings button crashes the app

### ISSUE THREAD

**Issue by cookies5219** [FireCubeStudios/Clippy#21]
trying to go to the settings just crashes it

**Comment by cookies5219** [comment]
its on 22h2 windows 11 (not insider) if that helps anything

**Comment by sthephanno1** [comment]
same but im on preview

**Comment by FireCubeStudios** [comment]
Looking into issue right now. It didn't seem to crash on Windows 10 for some users only 11

**Comment by FireCubeStudios** [comment]
Alright latest commit fixes crash. Stor eupdate coming in a few hours. Th eissue was related to #7
