### ISSUE TITLE
Clippy crashes when opening the settings window

### ISSUE THREAD

**Issue by ArmandDelessert** [FireCubeStudios/Clippy#24]
Clippy crashes whenever I try to open the settings window. Everything's fine when I launch Clippy, but when I try to open the settings window (to enter the OpenAI API key), a black window opens and the Clippy application crashes.

![Clippy Settings Window opening](https://github.com/FireCubeStudios/Clippy/assets/11057437/e04de3d0-9a4f-4850-9dcd-6acbe406a881)

I installed the app from the Windows Store. I am on Windows 11 22H2 (on an unofficially supported [CPU](https://ark.intel.com/content/www/us/en/ark/products/75462/intel-xeon-processor-e31245-v3-8m-cache-3-40-ghz.html)) :
![Windows 11 22H2 winver](https://github.com/FireCubeStudios/Clippy/assets/11057437/26d3ca57-141b-4385-8194-f59b87ae9774)

Here are the Windows event logs, I don't know if they will be useful :
[Clippy crashes 2023-07-07.zip](https://github.com/FireCubeStudios/Clippy/files/11983381/Clippy.crashes.2023-07-07.zip)

**Comment by FireCubeStudios** [comment]
This is an issue in 1.1.5.0 that has been fixed in 1.1.8.0
